"use strict";
let lname;
lname = "Santosh";
let newname = lname.toUpperCase();
console.log(newname);
let age;
age = 25;
age = 25.5;
let dob = "25";
let result = parseInt(dob);
let isValid = false;
let empList;
empList = ["Santosh", "Santosh1", "Santosh2"];
let numList; // ts generics
numList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
let results = numList.filter((num) => num > 2);
let num = numList.find((num) => num === 2);
let sum = numList.reduce((acc, num) => acc + num);
console.log(results);
console.log(num);
console.log(sum);
// lname = 10;
